
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
decorations = "None"
decorations_theme_variant = "Dark"
title = "Hi man, you really look at window titles"
dynamic_title = true

[font]
size = 8

[general]
import = [
  #"~/.config/alacritty/themes/themes/terafox.toml"
  #"~/.config/alacritty/themes/catppuccin-latte.toml"
  #"~/.config/alacritty/themes/catppuccin-frappe.toml"
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  #"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal]
